LCDForm
void LCDForm::updateWidget(Genie &genie, uint16_t wType, uint16_t wIndex, uint16_t wValue)
Referenced by LightControllerForm::updateWidgetsValues, TemperatureControllerForm::updateWidgetsValues.
void LCDForm::updateString(Genie &genie, uint16_t wIndex, String wValue)
Referenced by DebugFormClass::update.
virtual void LCDForm::init(Genie &genie)=0
virtual void LCDForm::update(Genie &genie)=0
Referenced by DisplayInterfaceClass::setCurrentForm, DisplayInterfaceClass::update.
virtual void LCDForm::onEvent(Genie &genie, genieFrame &evt)
Referenced by onEvent.
virtual void LCDForm::onEnter(Genie &genie)
Referenced by DisplayInterfaceClass::setCurrentForm.
virtual void LCDForm::onExit(Genie &genie)
Referenced by DisplayInterfaceClass::setCurrentForm.
virtual int LCDForm::getFormIndex()=0
Referenced by DisplayInterfaceClass::setCurrentForm.