ShellClass
ByteBuffer ShellClass::rxBuffer
Referenced by init, update.
Stream* ShellClass::serialPort
Referenced by init, update.
void ShellClass::init(Stream *serialPort)
References Endl, LoggerClass::i, Log, rxBuffer, serialPort, SHELL_RX_BUFFER, SHELL_TAG.
void ShellClass::update()
References ShellCommand::cmdFun, LoggerClass::e, Endl, findCmd, Log, rxBuffer, serialPort, SHELL_TAG.
void ShellClass::analogReadCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::analogWriteCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::channelListCmd(String &)
References channelsConfig, Endl, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelCount, Channel::getDataType, Channel::getID, Channel::getName, Channel::getSize, Hex, LoggerClass::i, Log, SHELL_TAG.
void ShellClass::channelValueCmd(String &)
References channelsBuffer, channelsConfig, LoggerClass::e, Endl, ChannelsConfigClass::getChannelByID, Channel::getID, ChannelsBufferClass::getValueAsByteArray, ChannelsBufferClass::getValueAsString, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::channelsValuesCmd(String &)
void ShellClass::digitalReadCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::digitalWriteCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::SDMkDirCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::SDOpenCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::SDRmCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::SDRmDirCmd(String &)
References LoggerClass::e, Endl, LoggerClass::i, Log, nextParam, SHELL_TAG.
void ShellClass::SDTreeCmd(String &)
References LoggerClass::e, Endl, Log, printSDTree, SHELL_TAG.
void ShellClass::CHbufferSet(String &)
References channelsBuffer, LoggerClass::e, Endl, Log, nextParam, ChannelsBufferClass::setValue, SHELL_TAG.
int ShellClass::findCmd(String &line, ShellCommand *cmd)
References CMDS_NUM, cmdsList, ShellCommand::cmdString.
Referenced by update.
String ShellClass::nextParam(String &params)
Referenced by analogReadCmd, analogWriteCmd, channelValueCmd, CHbufferSet, digitalReadCmd, digitalWriteCmd, SDMkDirCmd, SDOpenCmd, SDRmCmd, SDRmDirCmd.
void ShellClass::printSDTree(File dir, int indent)
References Endl, LoggerClass::i, Log, LoggerClass::repeat, SHELL_TAG.
Referenced by SDTreeCmd.