LoggerClass
byte LoggerClass::precision
Referenced by init, operator<<, setDecimalPrecision.
UARTClass* LoggerClass::serialPort
Referenced by assert, init, operator<<.
LogManip LoggerClass::mode
Referenced by init, operator<<.
void LoggerClass::init(UARTClass *serialPort)
References Dec, mode, precision, serialPort.
LoggerClass & LoggerClass::i(const char *tag="INFO")
References Info.
Referenced by LightInterfaceClass::allOff, ShellClass::analogReadCmd, ShellClass::analogWriteCmd, array, ShellClass::channelListCmd, ShellClass::channelValueCmd, HeaterInterface::cooldown, ShellClass::digitalReadCmd, ShellClass::digitalWriteCmd, ShellClass::init, LightInterfaceClass::init, HeaterInterface::init, CanInterfaceClass::init, ShellClass::printSDTree, repeat, ShellClass::SDMkDirCmd, ShellClass::SDOpenCmd, ShellClass::SDRmCmd, ShellClass::SDRmDirCmd, LightInterfaceClass::setColor, DisplayInterfaceClass::setCurrentForm, LightInterfaceClass::update, HeaterInterface::update, DataLoggerClass::update, CanInterfaceClass::update.
LoggerClass & LoggerClass::w(const char *tag="WARN")
References Warning.
Referenced by DisplayInterfaceClass::init, GeneralSwitchForm::onEvent, LightControllerForm::onEvent, TemperatureControllerForm::onEvent, LightInterfaceClass::setBrightness, ChannelsBufferClass::setValue, DisplayInterfaceClass::update.
LoggerClass & LoggerClass::e(const char *tag="ERR")
References Error.
Referenced by ShellClass::analogReadCmd, ShellClass::analogWriteCmd, assert, ShellClass::channelValueCmd, ShellClass::CHbufferSet, HeaterInterface::cooldown, DataLoggerClass::createNewLogFile, ShellClass::digitalReadCmd, ShellClass::digitalWriteCmd, ChannelsBufferClass::getValueAsString, ChannelsConfigClass::init, DataLoggerClass::init, ShellClass::SDMkDirCmd, ShellClass::SDOpenCmd, ShellClass::SDRmCmd, ShellClass::SDRmDirCmd, ShellClass::SDTreeCmd, ShellClass::update, HeaterInterface::update, DataLoggerClass::update, WifiInterfaceClass::update.
LoggerClass & LoggerClass::i(const __FlashStringHelper *tag)
References Info.
LoggerClass & LoggerClass::w(const __FlashStringHelper *tag)
References Warning.
LoggerClass & LoggerClass::e(const __FlashStringHelper *tag)
References Error.
void LoggerClass::setDecimalPrecision(int precision)
References precision.
LoggerClass& LoggerClass::array(T *a, int size)
References i.
Referenced by operator<<, WifiInterfaceClass::update.
LoggerClass & LoggerClass::repeat(char c, int times)
References i, Log.
Referenced by ShellClass::printSDTree.
void LoggerClass::assert(boolean condition, String msg)
References ASSERT_TAG, e, Endl, serialPort.
LoggerClass& operator<<(LoggerClass &log, byte value)
LoggerClass& operator<<(LoggerClass &log, char value)
LoggerClass& operator<<(LoggerClass &log, int value)
LoggerClass& operator<<(LoggerClass &log, unsigned int value)
LoggerClass& operator<<(LoggerClass &log, long value)
LoggerClass& operator<<(LoggerClass &log, unsigned long value)
LoggerClass& operator<<(LoggerClass &log, float value)
LoggerClass& operator<<(LoggerClass &log, double value)
LoggerClass& operator<<(LoggerClass &log, const char *value)
LoggerClass& operator<<(LoggerClass &log, String value)
LoggerClass& operator<<(LoggerClass &log, const __FlashStringHelper *value)
LoggerClass& operator<<(LoggerClass &log, LogManip value)
LoggerClass& operator<<(LoggerClass &log, LoggerClass &value)
LoggerClass& operator<<(LoggerClass &log, ByteBuffer &value)