CanInterfaceClass
Stream* CanInterfaceClass::debugSerial
Referenced by init, readFromDebugSerial, setCanDebugSerial, update, writePacketOnDebugSerial.
CAN_FRAME CanInterfaceClass::frame
Referenced by parseSerialDebugCmd, read, send, streamOverCan, update, waitForStreamOverCan.
ByteBuffer CanInterfaceClass::rxBuffer
Referenced by init, parseSerialDebugCmd, readFromDebugSerial.
CanEventHandler CanInterfaceClass::canEvent
Referenced by init, parseSerialDebugCmd, removeCanEventCallBack, setCanEventCallBack, update.
void CanInterfaceClass::init(int canSpeed, unsigned short minID=0, unsigned short maxID=2048)
References CAN_TAG, canEvent, DEBUG_RX_BUFFER_SIZE, debugSerial, Endl, LoggerClass::i, Log, rxBuffer.
void CanInterfaceClass::update()
References CAN_TAG, canEvent, debugSerial, Endl, frame, LoggerClass::i, Log, parseSerialDebugCmd, readFromDebugSerial, writePacketOnDebugSerial.
void CanInterfaceClass::setCanEventCallBack(CanEventHandler)
References canEvent.
void CanInterfaceClass::removeCanEventCallBack()
References canEvent.
int CanInterfaceClass::available()
CAN_FRAME & CanInterfaceClass::read()
References frame, writePacketOnDebugSerial.
Referenced by streamOverCan, waitForStreamOverCan.
void CanInterfaceClass::send(CanID::IDs id, byte *data, byte size)
References frame, writePacketOnDebugSerial.
Referenced by parseSerialDebugCmd, streamOverCan, waitForStreamOverCan.
CanStreamResult CanInterfaceClass::streamOverCan(CanID::IDs canID, const char *openStreamCmd, byte *buffer, int size)
References canInterface, CMD_TIMEOUT, ERROR, ERROR_CMD, frame, OK_CMD, PACKET_DELAY, read, send, SUCCES, TIMEOUT.
CanStreamResult CanInterfaceClass::waitForStreamOverCan(CanID::IDs canID, const char *openStreamCmd, byte *buffer, int expectedBytes)
References canInterface, CMD_TIMEOUT, ERROR, ERROR_CMD, frame, read, send, SUCCES, TIMEOUT, WRONG_ACK.
void CanInterfaceClass::setCanDebugSerial(Stream *debugSerial)
References debugSerial.
Referenced by DebugFormClass::onEvent.
void CanInterfaceClass::writePacketOnDebugSerial(CAN_FRAME &packet)
References CAD_MSG_HEADER, debugSerial.
Referenced by read, send, update.
void CanInterfaceClass::readFromDebugSerial()
References debugSerial, rxBuffer.
Referenced by update.
void CanInterfaceClass::parseSerialDebugCmd()
References CAN_MSG_HEADER, canEvent, frame, rxBuffer, send.
Referenced by update.