ChannelsBufferClass
unsigned short ChannelsBufferClass::bufferSize
Referenced by getBufferSize, init.
Vector<ByteBuffer> ChannelsBufferClass::buffer
Referenced by debug, getValueAs, getValueAsByteArray, getValueAsString, init, sendOnStream, setValue.
void ChannelsBufferClass::init()
References buffer, bufferSize, channelsConfig, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelCount, Channel::getSize.
void ChannelsBufferClass::debug()
References buffer, channelsConfig, ChannelsConfigClass::getChannelByIndex, Channel::name.
T ChannelsBufferClass::getValueAs(unsigned short id, T defaultValue)
References buffer, channelsConfig, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelIndex, Channel::hasTTLFinished, ChannelsConfigClass::isValid.
Referenced by HeaterInterface::update, LightInterfaceClass::update, TemperatureControllerForm::updateWidgetsValues.
T ChannelsBufferClass::getValueAs(unsigned short id)
References buffer, channelsConfig, ChannelsConfigClass::getChannelIndex, ChannelsConfigClass::isValid.
ByteBuffer ChannelsBufferClass::getValueAsByteArray(unsigned short id)
References buffer, channelsConfig, ChannelsConfigClass::getChannelIndex, ChannelsConfigClass::isValid.
Referenced by ShellClass::channelValueCmd.
String ChannelsBufferClass::getValueAsString(unsigned short id)
References Channel::BIT_FLAG, buffer, channelsConfig, CHBUF_TAG, Channel::DECIMAL, LoggerClass::e, Endl, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelIndex, Channel::getDataType, Channel::getSize, Channel::INTEGER, intToString, ChannelsConfigClass::isValid, Log, Channel::STRING, Channel::U_INTEGER, uintToString.
Referenced by ShellClass::channelValueCmd, LightInterfaceClass::setColor, DebugFormClass::update, DataLoggerClass::update.
boolean ChannelsBufferClass::isValueUpdated(unsigned short id)
References channelsConfig, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelIndex, Channel::hasTTLFinished, ChannelsConfigClass::isValid.
Referenced by DebugFormClass::update, DataLoggerClass::update.
void ChannelsBufferClass::setValue(unsigned short id, byte *data, unsigned short size)
References buffer, channelsConfig, CHBUF_TAG, Endl, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelIndex, Channel::getSize, ChannelsConfigClass::isValid, Log, Channel::resetTTLTimer, LoggerClass::w.
Referenced by ShellClass::CHbufferSet, LightInterfaceClass::init, GeneralSwitchForm::onEvent, TemperatureControllerForm::onEvent, LightInterfaceClass::setBrightness, LightInterfaceClass::setColor, setValue, WifiInterfaceClass::update.
void ChannelsBufferClass::setValue(unsigned short id, T value)
References setValue.
void ChannelsBufferClass::sendOnStream(UARTClass *stream)
References buffer, channelsConfig, ChannelsConfigClass::getChannelByIndex, ChannelsConfigClass::getChannelCount, Channel::getID.
unsigned short ChannelsBufferClass::getBufferSize()
References bufferSize.
String ChannelsBufferClass::uintToString(Channel *channel, byte *data)
References Channel::getSize.
Referenced by getValueAsString.
String ChannelsBufferClass::intToString(Channel *channel, byte *data)
References Channel::getSize.
Referenced by getValueAsString.