Channel
DataTypes
Attr
String Channel::name
Referenced by ChannelsBufferClass::debug, getName, setName.
byte Channel::size
Referenced by getSize, setSize.
unsigned short Channel::ID
Referenced by getID, setID.
DataTypes Channel::type
Referenced by getDataType, setDataType.
Timer Channel::ttlTimer
Referenced by Channel, hasTTLFinished, resetTTLTimer.
Channel::Channel()
References CH_BUFFER_TTL, ttlTimer.
void Channel::setSize(byte size)
References size.
Referenced by ChannelsConfigClass::init.
void Channel::setID(unsigned short ID)
References ID.
Referenced by ChannelsConfigClass::init.
void Channel::setDataType(DataTypes type)
References type.
Referenced by ChannelsConfigClass::init.
void Channel::setName(String name)
References name.
Referenced by ChannelsConfigClass::init.
byte Channel::getSize()
References size.
Referenced by ShellClass::channelListCmd, ChannelsConfigClass::debug, ChannelsBufferClass::getValueAsString, ChannelsBufferClass::init, ChannelsBufferClass::intToString, ChannelsBufferClass::setValue, ChannelsBufferClass::uintToString.
unsigned short Channel::getID()
References ID.
Referenced by ShellClass::channelListCmd, ShellClass::channelValueCmd, DataLoggerClass::createNewLogFile, ChannelsConfigClass::debug, ChannelsBufferClass::sendOnStream, DataLoggerClass::update.
Channel::DataTypes Channel::getDataType()
References type.
Referenced by ShellClass::channelListCmd, ChannelsConfigClass::debug, ChannelsBufferClass::getValueAsString.
String Channel::getName()
References name.
Referenced by ShellClass::channelListCmd, DataLoggerClass::createNewLogFile, ChannelsConfigClass::debug.
void Channel::resetTTLTimer()
References ttlTimer.
Referenced by ChannelsBufferClass::setValue.
bool Channel::hasTTLFinished()
References ttlTimer.
Referenced by ChannelsBufferClass::getValueAs, ChannelsBufferClass::isValueUpdated.