ChannelsConfigClass
boolean ChannelsConfigClass::valid
Referenced by init, isValid.
Vector<Channel*> ChannelsConfigClass::channels
Referenced by debug, getChannelByIndex, getChannelCount, getChannelIndex, init.
boolean ChannelsConfigClass::init()
References Channel::ATTR_COUNT, Channel::CanID, channels, CHANNELS_CFG_FILE, CHBUF_TAG, consoleForm, LoggerClass::e, Endl, Log, Channel::Name, ConsoleFormClass::println, Channel::setDataType, Channel::setID, Channel::setName, Channel::setSize, Channel::Size, Channel::Type, valid.
void ChannelsConfigClass::debug()
References channels, Endl, Channel::getDataType, Channel::getID, Channel::getName, Channel::getSize, Log.
Channel * ChannelsConfigClass::getChannelByID(unsigned short id)
References getChannelByIndex, getChannelIndex.
Referenced by ShellClass::channelValueCmd.
Channel * ChannelsConfigClass::getChannelByIndex(int index)
References channels.
Referenced by ShellClass::channelListCmd, DataLoggerClass::createNewLogFile, ChannelsBufferClass::debug, getChannelByID, ChannelsBufferClass::getValueAs, ChannelsBufferClass::getValueAsString, ChannelsBufferClass::init, ChannelsBufferClass::isValueUpdated, ChannelsBufferClass::sendOnStream, ChannelsBufferClass::setValue, DataLoggerClass::update.
int ChannelsConfigClass::getChannelIndex(unsigned short id)
References channels.
Referenced by getChannelByID, ChannelsBufferClass::getValueAs, ChannelsBufferClass::getValueAsByteArray, ChannelsBufferClass::getValueAsString, ChannelsBufferClass::isValueUpdated, ChannelsBufferClass::setValue.
int ChannelsConfigClass::getChannelCount()
References channels.
Referenced by ShellClass::channelListCmd, DataLoggerClass::createNewLogFile, ChannelsBufferClass::init, ChannelsBufferClass::sendOnStream, DataLoggerClass::update.
boolean ChannelsConfigClass::isValid()
References valid.
Referenced by ChannelsBufferClass::getValueAs, ChannelsBufferClass::getValueAsByteArray, ChannelsBufferClass::getValueAsString, ChannelsBufferClass::isValueUpdated, ChannelsBufferClass::setValue, DataLoggerClass::update.