LCDStringList
char LCDStringList::currentElement
Referenced by addElement, clear, down, getCurrentElement, init, up.
byte LCDStringList::widgetIndex
Referenced by getWidgetIndex, init, repaint.
byte LCDStringList::elementCount
Referenced by addElement, clear, down, getElementCount, init, up.
String LCDStringList::buffer
Referenced by addElement, clear, down, init, repaint, up.
Genie* LCDStringList::parent
Referenced by init, repaint.
void LCDStringList::init(byte index, int maxSize, Genie *parent)
References buffer, currentElement, elementCount, parent, widgetIndex.
void LCDStringList::up()
References buffer, currentElement, elementCount, repaint, SELECT_LINE_CHAR.
void LCDStringList::down()
References buffer, currentElement, elementCount, repaint, SELECT_LINE_CHAR.
void LCDStringList::clear()
References buffer, currentElement, elementCount, repaint.
void LCDStringList::addElement(String elem)
References buffer, currentElement, elementCount, SELECT_LINE_CHAR.
void LCDStringList::removeElement(int index)
int LCDStringList::getCurrentElement()
References currentElement.
int LCDStringList::getWidgetIndex()
References widgetIndex.
int LCDStringList::getElementCount()
References elementCount.
void LCDStringList::repaint()
References buffer, parent, widgetIndex.
Referenced by clear, down, up.