LCDStringMsg
byte LCDStringMsg::widgetIndex
Referenced by init, repaint.
String LCDStringMsg::buffer
Referenced by clear, getMessage, repaint, setMessage.
Genie* LCDStringMsg::parent
Referenced by init, repaint.
void LCDStringMsg::init(byte index, Genie *parent)
References parent, widgetIndex.
void LCDStringMsg::clear()
References buffer, repaint.
Referenced by setMessage.
const String & LCDStringMsg::getMessage()
References buffer.
void LCDStringMsg::repaint()
References buffer, parent, widgetIndex.
Referenced by clear, setMessage.
void LCDStringMsg::setMessage(String str)
References buffer, clear, repaint.
void LCDStringMsg::setMessage(const char *str)
References buffer, clear, repaint.