LightInterfaceClass
LIGHT LightInterfaceClass::roomLight
Referenced by allOff, init, setBrightness, update.
LIGHT LightInterfaceClass::awningLight
Referenced by allOff, init, setBrightness, update.
LIGHT LightInterfaceClass::worktopLight
Referenced by allOff, init, setBrightness, update.
HSV LightInterfaceClass::hsv
Referenced by init, setColor.
uint8_t LightInterfaceClass::fadeAmount
Referenced by allOff.
Timer LightInterfaceClass::ledTimer
Referenced by init, update.
Timer LightInterfaceClass::fadeTimer
Referenced by allOff.
void LightInterfaceClass::init()
References AWNING_LED, awningLight, LIGHT::b, channelsBuffer, Endl, LIGHT::g, HSV::h, CanID::HSV, hsv, LoggerClass::i, ledTimer, CanID::LIGHT_1, CanID::LIGHT_2, CanID::LIGHT_3, CanID::LIGHT_4, CanID::LIGHT_5, CanID::LIGHT_6, Log, LIGHT::r, RGB_BLUE, RGB_GREEN, RGB_RED, RGB_STATE_LED_DUR, RGB_TAG, roomLight, HSV::s, ChannelsBufferClass::setValue, HSV::v, LIGHT::w, WHITE_LED, WORKTOP_LED, worktopLight.
void LightInterfaceClass::update()
References AWNING_LED, awningLight, LIGHT::b, channelsBuffer, Endl, LIGHT::g, ChannelsBufferClass::getValueAs, CanID::HSV, LoggerClass::i, ledTimer, CanID::LIGHT_1, CanID::LIGHT_2, CanID::LIGHT_3, CanID::LIGHT_4, CanID::LIGHT_5, CanID::LIGHT_6, Log, LIGHT::r, RGB_BLUE, RGB_GREEN, RGB_RED, RGB_TAG, roomLight, setColor, LIGHT::w, WHITE_LED, WORKTOP_LED, worktopLight.
void LightInterfaceClass::setColor(double h)
References channelsBuffer, Endl, ChannelsBufferClass::getValueAsString, HSV::h, hsv, LoggerClass::i, CanID::LIGHT_1, CanID::LIGHT_2, CanID::LIGHT_3, Log, mapf, RGB_TAG, HSV::s, ChannelsBufferClass::setValue, HSV::v.
Referenced by LightControllerForm::onEvent, update.
void LightInterfaceClass::setBrightness(uint8_t brightness, uint8_t lightIndex)
References awningLight, channelsBuffer, Endl, CanID::LIGHT_4, CanID::LIGHT_5, CanID::LIGHT_6, Log, RGB_TAG, roomLight, ChannelsBufferClass::setValue, LIGHT::w, LoggerClass::w, worktopLight.
Referenced by LightControllerForm::onEvent.
void LightInterfaceClass::allOff()
References awningLight, LIGHT::b, fadeAmount, fadeTimer, LIGHT::g, LoggerClass::i, Log, LIGHT::r, RGB_TAG, roomLight, LIGHT::w, worktopLight.
Referenced by LightControllerForm::onEvent.
double LightInterfaceClass::mapf(double x, double in_min, double in_max, double out_min, double out_max)
Referenced by setColor.