ConsoleFormClass
Genie* ConsoleFormClass::genie
Referenced by addText, init.
String ConsoleFormClass::text
Referenced by addText, clear, init, print.
void ConsoleFormClass::init(Genie &genie)
References clear, genie, text, TEXT_BUFFER_SIZE.
Referenced by DisplayInterfaceClass::init.
void ConsoleFormClass::update(Genie &genie)
void ConsoleFormClass::print(String str)
References text.
void ConsoleFormClass::println(String str)
References addText.
Referenced by DataLoggerClass::createNewLogFile, ChannelsConfigClass::init, DataLoggerClass::init.
void ConsoleFormClass::clear()
References text.
Referenced by init.
int ConsoleFormClass::getFormIndex()
void ConsoleFormClass::addText(String str)
References CONSOLE_STR, genie, text, TEXT_BUFFER_SIZE.
Referenced by println.